apiVersion: v1
kind: Pod
metadata:
  name: k8-entrypoint
spec:
      containers:
      - name: k8-entrypoint
        image: k8-entrypoint:latest
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
            - /usr/sbin/k8-entrypoint
            - --ready
          initialDelaySeconds: 1
          periodSeconds: 5
        env:
          - name: DEPENDS_ON
            value: "etcd-cluster-client:client,kafka:client,zookeeper:server"
          - name: SERVICE_NAME
            value: "scout"
          - name: DC_SHORT_NAME
            value: "devgun"
        args:
        - /usr/sbin/k8-entrypoint
        - /usr/sbin/print-env
